#!/bin/bash

if pgrep compton &>/dev/null; then
    robot "shutting down Compton" & notify-send "Turning Compton OFF"
    pkill picom &
else
    robot "turning on picom" & notify-send "picom ON"
	picom -b --config /dev/null &
fi

exit 0
