#!/bin/bash
convert <input file> \
-fill none -draw "matte 0,0 reset" \
-tile <input file> \
-draw "roundRectangle -1,-1 <width>,<height> 30,30" \
( +clone -background black -shadow 80x5+10+10 ) \
+swap -background none -layers merge \
+repage <output file>

