#!/bin/sh
#
# simple - simple fetch script built on fetchutils
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.
reset=$(printf '\033[0m')
color1=$(printf '\033[1;31m')
format_info() {
    printf '%s%-10s %s%10s\n' "$color1" "$1:" \
        "$reset" "$2"
}
echo "
      ${USER}@$(hostname)

     $color1 tanggal $reset            :  "$(date)"
     $color1 sistem operasi $reset     :  "$(lsb_release -sirc)"
     $color1 versi kernel $reset       :  "$(uname -r)"
     $color1 shell $reset              :  "${SHELL##*/}"
     $color1 wm $reset                 :  dwm
     $color1 durasi aktif $reset       :  "$(~/Documents/scripts/system-uptime-pretty.sh)"
     $color1 jenis cpu $reset          :  Intel Celeron N3050
     $color1 jenis gpu $reset          :  Mesa DRI Intel(R) HD Graphics 400
     $color1 alokasi diska $reset      :  $(~/Documents/scripts/disk.sh)
     $color1 alokasi memori $reset     :  $(~/Documents/scripts/mem.sh)
     $color1 alokasi swap $reset       :  $(free -h | awk '/Swap/ {print $3 " " "/" " " $2}')
     $color1 tanggal instalasi $reset  :  $(ls -alct /|tail -1|awk '{print $7, $6,$8}')
"

